---
- name: Remove image and container
  block:
  - name: Remove container
    docker_container:
      name: "{{ name }}"
      image: "{{ username }}/{{ image }}"
      published_ports: "{{ ports }}"
      state: absent

  - name: Remove image
    docker_image:
      repository: "{{ username }}"
      name: "{{ image }}"
      state: absent

  when: web_app_full_wipe | bool
  tags:
    - wipe