version: "3.7"

networks:
  loki:

services:
  app_python:
    image: mierley4041/devops-flask:latest
    container_name: devops-flask
    ports:
      - 5000:5000
    logging:
      driver: "json-file"
      options:
        tag: "{{ .Name }}"
    networks:
      - loki

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./loki.yml:/etc/loki/config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    command:
      - "--config.file=/etc/promtail/config.yml"
      - "--config.expand-env=true"
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/datasources/ds.yml
    ports:
      - "3000:3000"
    networks:
      - loki