- name: Deploy Docker on Yandex Cloud
  hosts: all
  become: true

  vars:
    image_tag: "mierley4041/devops-flask:latest"

  roles:
    - ../../roles/docker

  tasks:
    - name: Run container
      ansible.builtin.shell: "docker run -d -p 80:5000 -t {{ image_tag|quote }}"