name: Python CI

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
       python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app_python/requirements.txt

    - name: Run tests
      run: |
        python -m unittest
      working-directory: app_python

    - name: Run Snyk check
      run: |
        npm install -g snyk
        snyk auth ${{ secrets.SNYK_TOKEN }}
        snyk test
      working-directory: app_python

    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      run: |
        cd app_python
        docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/devops-course --push .
